services:
  weaviate:
    environment:
      WEAVIATE_AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
      WEAVIATE_AUTHENTICATION_APIKEY_ENABLED: "true"
      WEAVIATE_AUTHENTICATION_APIKEY_ALLOWED_KEYS: "catbQGyHUC973ycyQrs5G5RA"
      WEAVIATE_AUTHENTICATION_APIKEY_USERS: "admin"
